// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSANS_12_FONT_ID (1842047136)
#define NOTOSANS_14_FONT_ID (-771966302)
#define NOTOSANS_16_FONT_ID (1908747114)
#define NOTOSANS_18_FONT_ID (-1305026079)
#define NOTOSERIF_12_FONT_ID (-885528155)
#define NOTOSERIF_14_FONT_ID (-94948752)
#define NOTOSERIF_16_FONT_ID (903888320)
#define NOTOSERIF_18_FONT_ID (-1592293404)
#define SMALL_FONT_ID (-1377778950)
#define UI_10_FONT_ID (98875687)
#define UI_12_FONT_ID (2063773289)

static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
